<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Produto_estoque extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Produto_estoque_model');
    } 

    /*
     * Listing of produto_estoque
     */
    function index()
    {
        $data['produto_estoque'] = $this->Produto_estoque_model->get_all_produto_estoque();
        $this->load->view('produto_estoque/index',$data);
    }

    /*
     * Adding a new produto_estoque
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'data_criacao' => $this->input->post('data_criacao'),
				'quantidade' => $this->input->post('quantidade'),
				'quantidade_baixa' => $this->input->post('quantidade_baixa'),
				'produto_id' => $this->input->post('produto_id'),
            );
            
            $produto_estoque_id = $this->Produto_estoque_model->add_produto_estoque($params);
            redirect('produto_estoque/index');
        }
        else
        {

			$this->load->model('Produto_model');
			$data['produto'] = $this->Produto_model->get_all_produto();
                
            $this->load->view('produto_estoque/add',$data);
        }
    }  

    /*
     * Editing a produto_estoque
     */
    function edit($id)
    {   
        // check if the produto_estoque exists before trying to edit it
        $produto_estoque = $this->Produto_estoque_model->get_produto_estoque($id);
        
        if(isset($produto_estoque['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'data_criacao' => $this->input->post('data_criacao'),
					'quantidade' => $this->input->post('quantidade'),
					'quantidade_baixa' => $this->input->post('quantidade_baixa'),
					'produto_id' => $this->input->post('produto_id'),
                );

                $this->Produto_estoque_model->update_produto_estoque($id,$params);            
                redirect('produto_estoque/index');
            }
            else
            {   
                $data['produto_estoque'] = $this->Produto_estoque_model->get_produto_estoque($id);
    
				$this->load->model('Produto_model');
				$data['produto'] = $this->Produto_model->get_all_produto();

                $this->load->view('produto_estoque/edit',$data);
            }
        }
        else
            show_error('The produto_estoque you are trying to edit does not exist.');
    } 

    /*
     * Deleting produto_estoque
     */
    function remove($id)
    {
        $produto_estoque = $this->Produto_estoque_model->get_produto_estoque($id);

        // check if the produto_estoque exists before trying to delete it
        if(isset($produto_estoque['id']))
        {
            $this->Produto_estoque_model->delete_produto_estoque($id);
            redirect('produto_estoque/index');
        }
        else
            show_error('The produto_estoque you are trying to delete does not exist.');
    }
    
}
