<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Usuario extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Usuario_model');
    } 

    /*
     * Listing of usuario
     */
    function index()
    {
        $data['usuario'] = $this->Usuario_model->get_all_usuario();
        $this->load->view('cabecalho');
        $this->load->view('usuario/index',$data);
    }

    /*
     * Adding a new usuario
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('nome_usuario','Nome Usuario','required');
        
        if($this->form_validation->run())     
        {   
            $params = array(
                'data_criacao' => date('Y-m-d'),
                'nome_usuario' => $this->input->post('nome_usuario'),
            );
            
            $usuario_id = $this->Usuario_model->add_usuario($params);
            redirect('usuario/index');
        }
        else
        {
            $this->load->view('cabecalho');
            $this->load->view('usuario/add');
        }
    }  

    /*
     * Editing a usuario
     */
    function edit($id)
    {   
        // check if the usuario exists before trying to edit it
        $usuario = $this->Usuario_model->get_usuario($id);
        
        if(isset($usuario['id']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('nome_usuario','Nome Usuario','required');
        
            if($this->form_validation->run())     
            {   
                $params = array(
                    'nome_usuario' => $this->input->post('nome_usuario'),
                );

                $this->Usuario_model->update_usuario($id,$params);            
                redirect('usuario/index');
            }
            else
            {   
                $data['usuario'] = $this->Usuario_model->get_usuario($id);
                $this->load->view('cabecalho');
                $this->load->view('usuario/edit',$data);
            }
        }
        else
            show_error('O usuário não existe.');
    } 

    /*
     * Deleting usuario
     */
    function remove($id)
    {
        $usuario = $this->Usuario_model->get_usuario($id);

        // check if the usuario exists before trying to delete it
        if(isset($usuario['id']))
        {
            $this->Usuario_model->delete_usuario($id);
            redirect('usuario/index');
        }
        else
            show_error('O usuário que você quer deletar não existe.');
    }
    
}
