<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Compra_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get compra by id
     */
    function get_compra($id)
    {
        return $this->db->get_where('compra',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all compra
     */
    function get_all_compra()
    {
        return $this->db->get('compra')->result_array();
    }
    
    /*
     * function to add new compra
     */
    function add_compra($params)
    {
        $this->db->insert('compra',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update compra
     */
    function update_compra($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('compra',$params);
    }
    
    /*
     * function to delete compra
     */
    function delete_compra($id)
    {
        $this->db->delete('compra',array('id'=>$id));
    }
}
