<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Fornecedor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fornecedor by id
     */
    function get_fornecedor($id)
    {
        return $this->db->get_where('fornecedor',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all fornecedor
     */
    function get_all_fornecedor()
    {
        return $this->db->get('fornecedor')->result_array();
    }
    
    /*
     * function to add new fornecedor
     */
    function add_fornecedor($params)
    {
        $this->db->insert('fornecedor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fornecedor
     */
    function update_fornecedor($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('fornecedor',$params);
    }
    
    /*
     * function to delete fornecedor
     */
    function delete_fornecedor($id)
    {
        $this->db->delete('fornecedor',array('id'=>$id));
    }
}
