<?php
/* 
 * Generated by CRUDigniter v2.1 Beta 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by id
     */
    function get_usuario($id)
    {
        return $this->db->get_where('usuario',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all usuario
     */
    function get_all_usuario()
    {
        return $this->db->get('usuario')->result_array();
    }
    
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('usuario',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($id)
    {
        $this->db->delete('usuario',array('id'=>$id));
    }

    function estaSalvo($usuario) {
        $this->db->where("nome_usuario",$usuario);
        $query = $this->db->get("usuario");
        
        if ($query->num_rows() > 0) {
            return true;
        }
        else {
            return false;
        }
    }
}
